# coding: utf-8

"""
    Steam Scraper

    Scrapes roms from screenscraper.fr for steam-rom-manager

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from fastapi import FastAPI
import steam_scraper_server.apis.scrape_api as scrape_api
import steam_scraper_server.apis.security_api as security_api
from tortoise.contrib.fastapi import register_tortoise

app = FastAPI(
    title="Steam Scraper",
    description="Api for using screenscraper.fr in steam rom manager",
    version="1.0.0",
    root_path="/scraper/api"
)

register_tortoise(
    app,
    db_url="sqlite:///opt/scraper/db/db.sqlite3",
    modules={
        "models": [
            "steam_scraper_server.db.user",
            "steam_scraper_server.db.rom"
        ]
    },
    generate_schemas=True,
    add_exception_handlers=True
)
app.include_router(scrape_api.router)
app.include_router(security_api.router)

