# coding: utf-8

"""
    Steam Scraper

    Scrapes roms from screenscraper.fr for steam-rom-manager

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from fastapi import FastAPI

from steam_scraper_server.apis.scrape_api import router as ScrapeApiRouter

app = FastAPI(
    title="Steam Scraper",
    description="Api for using screenscraper.fr in steam rom manager",
    version="1.0.0"
)

app.include_router(ScrapeApiRouter)
